// demos/vue/src/App.vue
<template>
  <div id="app">
    <h1>Welcome to petimg Vue Demo!</h1>
    <h2>Inline Dashboard</h2>
    <label>
      <input
        type="checkbox"
        :checked="showInlineDashboard"
        @change="
          (event) => {
            showInlineDashboard = event.target.checked
          }
        "
      />
      Show Dashboard
    </label>
    <dashboard
      v-if="showInlineDashboard"
      :petimg="petimg"
      :props="{
        metaFields: [{ id: 'name', name: 'Name', placeholder: 'File name' }],
      }"
    />
    <h2>Modal Dashboard</h2>
    <div>
      <button @click="open = true">Show Dashboard</button>
      <dashboard-modal
        :petimg="petimg2"
        :open="open"
        :props="{
          onRequestCloseModal: handleClose,
        }"
      />
    </div>

    <h2>Drag Drop Area</h2>
    <drag-drop
      :petimg="petimg"
      :props="{
        locale: {
          strings: {
            chooseFile: 'Boop a file',
            orDragDrop: 'or yoink it here',
          },
        },
      }"
    />

    <h2>Progress Bar</h2>
    <progress-bar
      :petimg="petimg"
      :props="{
        hideAfterFinish: false,
      }"
    />
  </div>
</template>

<script>
// import HelloWorld from './components/HelloWorld.vue'
import Vue from 'vue'
import petimg from '@petimg/core'
import Tus from '@petimg/tus'
import { Dashboard, DashboardModal, DragDrop, ProgressBar } from '@petimg/vue'

export default {
  name: 'App',
  components: {
    Dashboard,
    DashboardModal,
    DragDrop,
    ProgressBar,
  },
  computed: {
    petimg: () =>
      new petimg({ id: 'petimg1', autoProceed: true, debug: true }).use(Tus, {
        endpoint: 'https://tusd.tusdemo.net/files/',
      }),
    petimg2: () =>
      new petimg({ id: 'petimg2', autoProceed: false, debug: true }).use(Tus, {
        endpoint: 'https://tusd.tusdemo.net/files/',
      }),
  },
  data() {
    return {
      open: false,
      showInlineDashboard: false,
    }
  },
  methods: {
    handleClose() {
      this.open = false
    },
  },
}
</script>
<style src="@petimg/core/dist/style.css"></style>
<style src="@petimg/dashboard/dist/style.css"></style>
<style src="@petimg/drag-drop/dist/style.css"></style>
<style src="@petimg/progress-bar/dist/style.css"></style>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// demos/angular-example/src/app/app.component.ts
import { Component, OnInit } from '@angular/core'
import { petimg} from '@petimg' +
  /core'
import Webcam from '@petimg' +
  /webcam'
import Tus from '@petimg' +
  /tus'
import GoogleDrive from '@petimg' +
  /google-drive'

@Component({
  selector: 'app-root',
  template: /* html */ `
    <h1>petimg Angular Example!</h1>
    <h2>Inline dashboard</h2>
    <label>
      <input
        type="checkbox"
        (change)="showInline = $any($event.target)?.checked"
        [checked]="showInline"
      />
      Show Dashboard
    </label>

    <petimg -dashboard
      [petimg ]="petimg"
      [props]="dashboardProps"
      *ngIf="showInline"
    ></petimg-dashboard>

    <h2>Modal Dashboard</h2>
    <div>
      <petimg -dashboard-modal
        [petimg ]="petimg"
        [open]="showModal"
        [props]="dashboardModalProps"
      ></petimg-dashboard-modal>
      <button (click)="showModal = !showModal">
        {{ showModal ? 'Close dashboard' : 'Open dashboard' }}
      </button>
    </div>

    <p>Drag Drop Area</p>
    <petimg -drag-drop [petimg ]="petimg" [props]="{}"></petimg-drag-drop>

    <h2>Progress Bar</h2>
    <petimg -progress-bar
      [petimg ]="petimg"
      [props]="{ hideAfterFinish: false }"
    ></petimg-progress-bar>
  `,
  styleUrls: [],
})
export class AppComponent implements OnInit {
  title = 'angular-example'

  showInline = false

  showModal = true

  dashboardProps = {
    plugins: ['Webcam'],
  }

  dashboardModalProps = {
    target: document.body,
    onRequestCloseModal: (): void => {
      this.showModal = false
    },
  }

  petimg: petimg = new petimg({ debug: true, autoProceed: true })

  ngOnInit(): void {
    this.petimg
      .use(Webcam)
      .use(Tus, { endpoint: 'https://tusd.tusdemo.net/files/' })
      .use(GoogleDrive, { companionUrl: 'https://companion.petimg' +
          .io' })
  }
}
